notes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns=[
    path('', views.note_list, name='note_list'),
    re_path('^notes/?$', views.note_redirect, name='note_redirect'),
    path('notes/<slug:note_slug>', views.note_detail, name='note_detail'),
    path('archive/', views.archive_main, name='archive_main'),
    path('archive/<int:archive_year>/', views.archive_year, name='archive_year'),
    path('archive/<int:archive_year>/<int:archive_month>/', views.archive_month, name='archive_month'),
]

pcdenotes/urls.py
from django.contrib import admin
from django.urls import path, include

from filebrowser.sites import site

urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
]

notes/models.py
from django.db import models
from django.db.models import Count
from django.db.models.functions import ExtractYear, ExtractMonth, Coalesce
from django.db.models.signals import pre_save

from django.dispatch import receiver
from django.contrib.auth.models import User
from django.urls import reverse

from datetime import datetime

# Create your models here.

NOTE_STATUS = ((0, "Draft"),
               (1, "Published"))            

class NoteQuerySet(models.QuerySet):
    pass

class NoteManager(models.Manager):
    def all_published(self):
        return super().get_queryset().filter(status=1).annotate(publication_date=Coalesce('published_at', 'created_at')).order_by('-publication_date')

    def all(self):
        return super().all().annotate(publication_date=Coalesce('published_at', 'created_at')).order_by('-publication_date')

    def per_year(self, year):
        return self.all_published().filter(publication_date__year=year)

    def per_month(self, year, month):
        return self.per_year(year).filter(publication_date__month=month)

    def years(self):
        return self.all_published().annotate(published_year=ExtractYear('publication_date')).values_list('published_year', flat=True).distinct().order_by('published_year')

    def years_with_total(self):
        return self.all_published().annotate(published_year=ExtractYear('publication_date')).values('published_year').annotate(total=Count('id')).order_by('published_year').values('published_year', 'total').distinct()

    def months(self, year):
        return self.per_year(year).annotate(published_month=ExtractMonth('publication_date')).values_list('published_month', flat=True).distinct().order_by('published_month')

    def months_with_total(self, year):
        return self.per_year(year).annotate(published_month=ExtractMonth('publication_date')).values('published_month').annotate(total=Count('id')).order_by('published_month').values('published_month', 'total').distinct()

class Note(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes_posted')
    content = models.TextField()
    status = models.IntegerField(choices=NOTE_STATUS, default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True, editable=False)

    objects = NoteManager()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("notes:note_detail", kwargs={"note_slug": self.slug})

    def is_draft(self):
        return self.status == 0

    def is_published(self):
        return self.status == 1

@receiver(pre_save, sender=Note)
def note_pre_save(sender, instance, **kwargs):
    if instance.pk is None:
        if instance.status == 1:
            instance.published_at = datetime.now()
    else:
        old_instance = Note.objects.get(pk=instance.pk)
        
        if old_instance.status == 0 and instance.status == 1:
            instance.published_at = datetime.now()

notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models.functions import ExtractYear, ExtractMonth

from pcdenotes.settings import NOTES_PER_PAGE
from .models import Note

# Create your views here.

def note_list(request):
    notes = Note.objects.all() if request.user.is_staff else Note.objects.all_published()

    notes_count = notes.count()
    paginator = Paginator(notes, NOTES_PER_PAGE)

    page_number = 1

    try:
        page_number = int(request.GET.get('page'))
    except:
        pass

    page_count = paginator.num_pages
    
    notes_page = paginator.get_page(page_number)

    return render(request, 'note_list.html', {'notes_page': notes_page, 'notes_count': notes_count, 'pages': paginator, 'page_number': page_number, 'page_count': page_count})

def note_redirect(request):
    return redirect('notes:note_list', permanent=True)

def note_detail(request, note_slug):
    note = get_object_or_404(Note, slug=note_slug) if request.user.is_staff else get_object_or_404(Note, slug=note_slug, status=1)
    return render(request, 'note_detail.html', {'note': note})

def archive_main(request):
    notes_years = Note.objects.years_with_total()
    return render(request, 'archive_main.html', {'years': notes_years})

def archive_year(request, archive_year):
    notes_months = Note.objects.months_with_total(archive_year)
    return render(request, 'archive_year.html', {'year': archive_year, 'months': notes_months})

def archive_month(request, archive_year, archive_month):
    notes = Note.objects.per_month(archive_year, archive_month)
    return render(request, 'archive_month.html', {'year': archive_year, 'month': archive_month, 'notes': notes})

notes/templates/archive_main.html
{% extends "note_base.html" %}

{% block title %}Archive – Notes{% endblock %}

{% block content %}
<h2>Archive</h2>

{% if years %}
<ul>
  {% for year in years %}
    <li><a href="{{ year.published_year }}/">{{ year.published_year }}</a> ({{ year.total }})</li>
  {% endfor %}
</ul>
{% else %}
<p>No notes</p>
{% endif %}
{% endblock %}

notes/templates/archive_month.html
{% extends "note_base.html" %}
{% load notes_extras %}

{% block title %}Archive {{ month|month_name}} {{ year }} – Notes{% endblock %}

{% block content %}
<h2>Archive {{ month|month_name }} {{ year }}</h2>

{% if notes %}
<ul>
  {% for note in notes %}
    <li><a href="{{ note.get_absolute_url }}">{{ note.title }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No notes</p>
{% endif %}
{% endblock %}

notes/templates/archive_year.html
{% extends "note_base.html" %}
{% load notes_extras %}

{% block title %}Archive {{ year }} – Notes{% endblock %}

{% block content %}
<h2>Archive {{ year }}</h2>

{% if months %}
<ul>
  {% for month in months %}
    <li><a href="{{ month.published_month }}/">{{ month.published_month|month_name }}</a> ({{ month.total }})</li>
  {% endfor %}
</ul>
{% else %}
<p>No notes</p>
{% endif %}
{% endblock %}

notes/templates/note.html
{% load notes_extras %}
<article{% if note.is_draft %} class="text-muted"{% endif %}>
    <h2><a href="{{ note.get_absolute_url }}"{% if note.is_draft %} class="text-muted"{% endif %}>{{ note.title }}</a></h2>
    {% if note.is_draft %}<p class="fw-bold">Status: Draft</p>{% endif %}
    <div>{{ note.content|markdown|safe }}</div>
    <p class="publication-date">Published on {{ note.publication_date|date:"Y-m-d, H:i O" }}</p>
</article>

notes/templates/note_base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="{% static "notes/style.css" %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="d-flex flex-column min-vh-100">

  <header class="container-fluid p-5">
    <h1><a href="{% url "notes:note_list" %}">Notes</a></h1>
  </header>

  <main class="container flex-fill">
    {% block content %}{% endblock %}
  </main>

  <footer class="container-fluid pt-5 pb-5 ps-md-5 pe-md-5 mt-5">
    <div class="row">
      <div id="footer-left" class="col-lg-4 col-md-12 col-sm-12">
        <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangopowered126x54.gif" width="126" height="54" alt="Powered by Django." title="Powered by Django." /></a>
      </div>
      <div id="footer-middle" class="col-lg-4 col-md-12 col-sm-12">
        <ul>
          <li><a href="{% url "notes:note_list" %}">Home</a></li>
          <li><a href="{% url "notes:archive_main" %}">Archive</a></li>
        </ul>
      </div>
      <div id="footer-right" class="col-lg-4 col-md-12 col-sm-12">
        This site contains random notes and thoughts by Patrick Canterino.<br>
        If you have any questions, you may write me an email: <a href="mailto:patrick@patrick-canterino.de">patrick@patrick-canterino.de</a>
      </div>
    </div>
    <div id="copyright">
      {% with year_start="2022" %}
      {% now "Y" as year_current %}
      © {% if year_current > year_start %}{{ year_start }}-{% endif %}{{ year_current }} <a href="https://www.patrick-canterino.de/">Patrick Canterino</a> | Content is licensed under <a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC BY 4.0</a>
      {% endwith %}
    </div>
    <div id="footer-note">
      Powered by <a href="https://github.com/pcanterino/pcdenotes">PCDENotes</a>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

notes/templates/note_detail.html
{% extends "note_base.html" %}

{% block title %}{{ note.title }} – Notes{% endblock %}

{% block content %}
{% include "note.html" %}
{% endblock %}

notes/templates/note_list.html
{% extends "note_base.html" %}

{% block title %}Notes{% endblock %}

{% block content %}
  {% for note in notes_page %}
  {% include "note.html" %}
  {% empty %}
  <p>No notes</p>
  {% endfor %}

  {% if page_count > 1 %}
    <ul class="pagination flex-wrap mt-5">
      {% for page in pages %}
        {% if page.number != page_number %}
          <li class="page-item"><a href="?page={{ page.number }}" class="page-link">{{ page.number }}</a></li>
        {% else %}
          <li class="page-item active"><span class="page-link">{{ page.number }}</span></li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}